config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  concern :votable do
    resources :votes, only: [:create, :update]
  end

  resources :languages

  resources :links, concerns: :votable do
    resources :comments, concerns: :votable
  end

  # You can have the root of your site routed with "root"
  root 'links#index'

  get 'links_by_lang' => 'links#index_by_language'
  # post 'linksvotes' => 'votes#createLinkVote'
  # post 'commentsvotes' => 'votes#createCommentVote'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
	belongs_to :link
	has_many :votes, :as => :votable

end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :links
end

app/models/link.rb
class Link < ActiveRecord::Base

	belongs_to :user
	has_many :comments
	has_many :votes, :as => :votable
	belongs_to :language


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
  has_many :comments, through: :links
  has_many :votes

  def already_voted_this?(context, context_type)
      return self.votes.where(votable_type: context_type, votable_id: context.id).first != nil
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :votable, polymorphic: true
	belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@link = Link.find(params[:link_id])
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id 
		@comment.link_id = @link.id

		if @comment.save
			redirect_to @link
		else
			render :template =>  'links/show'
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:text, :vote_count)
	end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

	def show
		@language = Language.find(params[:id])
		@links = Link.where(language: @language).order("vote_count DESC")
	end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	def index
		@links = Link.all.order("vote_count DESC")
	end


	def show
		@link = Link.find(params[:id])
		@comment = Comment.new
		@comments = @link.comments.order("vote_count DESC")
	end

	def new
		return redirect_to '/', alert: "Login or Signup first" unless current_user
    @link = current_user.links.build
    @languages = Language.all
    # @language = @languages.each{ |language| language.name}
	end

	def create
    return redirect_to '/', alert: "Login or Signup first" unless current_user

    @link = current_user.links.build(link_params)
    if @link.save
      redirect_to link_path(@link)
    else
      redirect_to new_link_path, :alert => @link.errors.full_messages.join(". ")
    end
	end

	def link_params
		params.require(:link).permit(:title, :url, :language_id, :user_id, :vote_count)
	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @context = context_obj
    @vote = Vote.new(user_id: current_user.id, votable_id: @context.id, votable_type: context_type)
    if current_user.already_voted_this?(@context, context_type)
      redirect_to context_path
    else
      @vote.save
      @context.update(vote_count: @context.vote_count + 1)
      redirect_to context_path
    end
  end


  private
  def vote_params
    params.require(:vote).permit(:user_id, :votable_id)
  end

  def votable_is_comment?
    params[:comment_id] ? true : false
  end

  def context_obj
    votable_is_comment? ? Comment.find(params[:comment_id]) : Link.find(params[:link_id])
  end

  def context_type
    votable_is_comment? ? "Comment" : "Link"
  end

  def context_path
      votable_is_comment? ? link_path(context_obj.link) : link_path(context_obj)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for [@link, @comment] do |f| %>
<%= f.text_area :text, :size => "31x7" %> <br>
<%= f.submit "New Comment", class:"btn btn-default" %>
<% end %>

app/views/comments/_index.html.erb
<% @link.comments.order("vote_count DESC").each do |c| %>
<div class="comment">
  <% c_votes = c.vote_count == nil ? 0 : c.vote_count %>

  <div id="comment_credentials">
    <span id="comment_label">COMMENT</span>
    <span id="comment_votes"><%= c_votes %></span>
    <span id="comment_email"><%= c.user.email %></span>

    <% if current_user %>
      <%= form_tag("/links/#{@link.id}/comments/#{c.id}/votes", method: "post") do %>
        <br><span id="like_button"><%= submit_tag("Like", class:"btn btn-default") %></span><br><br>
        <% end %>
    <% end %>
  </div>

  <% time = c.created_at.in_time_zone("Eastern Time (US & Canada)") %>
  <p id="comment_text"><%= c.text %></p>
  <p id="comment_time"><%= time.strftime("%m/%d/%Y %I:%M%p") %></p><br>
</div>
<% end %>

app/views/languages/show.html.erb
<div class="link_list">

	<%= render "shared/filter" %>


  <% @links.each do |l| %>

    <p>
    	<%= l.title %> <br><strong><%= l.language.name %></strong>
    		:  <%= l.url %><br> 
    	<%= link_to 'Show Link', link_path(l) %>
    	 [<%= l.vote_count %>]
    	
    </p>

  <% end %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edhacks</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

    <title>Edful</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <%= render "shared/nav"%>
      <%= yield %>
    </div>

  </body>
</html>

app/views/links/index.html.erb
<div class="link_list">
	<%= render "shared/filter" %>
	
  <% @links.each do |l| %>

    <p>
    	<%= l.title %> <br><strong><%= l.language.name %></strong>
    		:  <%= l.url %><br> 
    	<%= link_to 'Show Link', link_path(l) %>
    	 [<%= l.vote_count %>]
    	
    </p>

  <% end %>
<div>

app/views/links/new.html.erb
<%= form_for @link do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :language %><br>
    <%= f.collection_select(:language_id, Language.all, :id, :name) %>
  </p>

  <p>
    <%= f.submit %>
  </p>


<% end %>

app/views/links/show.html.erb
<div class="show"> 
<h1 id="link_title"><%= @link.title %> </h1>


<br>

    <% if current_user %>
    <div id="link_votes">
      <%= form_for [@link, Vote.new] do |f| %>
        <span id="link_vote_count"><%= f.label "#{@link.vote_count} votes" %></span> <br>
        <%= f.submit "Like!", class:"btn btn-default"%> <br>
        <br>
      <% end %>
    </div>
    <% end %>

<%= @link.title %><br>
<%= @link.language.name %><br>
<%= link_to @link.url, @link.url %><br>

  <div id="back_to_links_index"><%= link_to "Back", root_url %></div><br>

  <h3>Comments</h3>
    <% if current_user %>
      <%= render partial: "comments/form" %>
    <% end %><br><br>
    <%= render partial: "comments/index", object: @link.comments %>    
</div>

app/views/shared/_filter.html.erb
<div class="filter">

	<% @languages = Language.all %>

<ul class="nav nav-tabs" role="tablist">
	<li><%= link_to "Home", root_path %> <li>
	<% @languages.each do |lang| %>
		<li><%= link_to lang.name, language_path(lang) %></li>
	<% end %>
</ul>
</div>

app/views/shared/_nav.html.erb
<div class="header">
	<% if user_signed_in? %>
		<div class="row">
		    <div class="name col-md-9">
	    	  <%= link_to 'Edful', root_path%>
	    	  						<h4><%= "[Hackathon edition]"  %></h4>
		    </div>

			<div class="col-md-3"> 
			  <%= link_to 'Create new link', new_link_path, class: "btn btn-default"%> 
			  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-default" %>
			</div>

		    </div>

	<% else %>
	<div class="row">
	    <div class="name col-md-9">
    	  <%= link_to 'Edful', root_path%>
    	  
    	  <h4><%= "[Hackathon edition]"  %></h4>
	    </div>

		<div class="col-md-3">
		  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-default" %>
		  <%= link_to "Login", new_user_session_path, class: "btn btn-default" %>
		</div>
	    </div>
		
	<% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>